FROM java:8
VOLUME /tmp
COPY target/security-0.0.1-SNAPSHOT.jar security-0.0.1-SNAPSHOT.jar
RUN bash -c "touch /security-0.0.1-SNAPSHOT.jar"
EXPOSE 9999
ENTRYPOINT ["java","-jar","security-0.0.1-SNAPSHOT.jar"]
